CREATE TABLE users_data
(
    chat_id       SERIAL PRIMARY KEY,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    user_name     VARCHAR(255),
    photo_url     VARCHAR(255),
    date_of_birth DATE,
    registered_at TIMESTAMP
);

CREATE TABLE groups(
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE user_groups (
    chat_id BIGINT REFERENCES users_data(chat_id),
    group_id BIGINT REFERENCES groups(group_id),
    PRIMARY KEY (chat_id, group_id)
);